<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>Cast.NET</Product>
    <PackageId>Cast.NET</PackageId>
    <Description>A .NET library for reading and writing Cast files.</Description>
    <PackageTags>cast;3d;model;animation;gamedev;file-format</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Scobalula/Cast.NET</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Scobalula/Cast.NET</RepositoryUrl>
    <PackageReleaseNotes>https://github.com/Scobalula/Cast.NET/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cast.NET.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\img\logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
